
server:
  port: 5544

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"

zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    pagamentos:
      stripPrefix: false
      path: /pagamentos/**
    distancia:
      stripPrefix: false
      path: /distancia/**
    autorizacao:
      path: /login/**
    monolito:
      path: /**

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user